### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by marceloschmitt** [OCLC-Research/oclcsrw#3]
When I try to install I get the following errors:

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project SRW: Compilation failure: Compilation failure:
[ERROR] /home/marcelo/oclcsrw-master/src/main/java/ORG/oclc/os/SRW/OpenSearchQueryResult.java:[56,21] error: cannot find symbol
[ERROR] symbol:   variable defaultSchemaID
[ERROR] location: variable db of type SRWOpenSearchDatabase
[ERROR] /home/marcelo/oclcsrw-master/src/main/java/ORG/oclc/os/SRW/OpenSearchQueryResult.java:[58,21] error: cannot find symbol
[ERROR] symbol:   variable defaultSchemaName
[ERROR] location: variable db of type SRWOpenSearchDatabase
[ERROR] /home/marcelo/oclcsrw-master/src/main/java/ORG/oclc/os/SRW/OpenSearchQueryResult.java:[77,40] error: incompatible types: Templates cannot be converted to String
[ERROR] /home/marcelo/oclcsrw-master/src/main/java/ORG/oclc/os/SRW/OpenSearchQueryResult.java:[113,29] error: cannot find symbol
[ERROR] symbol:   variable itemsPerPage
[ERROR] location: variable db of type SRWOpenSearchDatabase
[ERROR] /home/marcelo/oclcsrw-master/src/main/java/ORG/oclc/os/SRW/OpenSearchQueryResult.java:[115,38] error: cannot find symbol
[ERROR] -> [Help 1]
 
Any idea?

**Comment by ralphlevan** [comment]
Delete that class. It was an incomplete experiment that probably shouldn't have been committed.

Sorry!

Ralph

________________________________

**Comment by marceloschmitt** [comment]
Thanks. It installed, but when a search for something, I got an error related to commons-pool. But, when I try to search, I got the following error:

org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) at java.lang.Thread.run(Thread.java:748) Caused by: java.lang.NoClassDefFoundError: org/apache/commons/pool/ObjectPool at org.dspace.storage.rdbms.DatabaseManager.initialize(DatabaseManager.java:1727) at org.dspace.storage.rdbms.DatabaseManager.getConnection(DatabaseManager.java:597) at org.dspace.core.Context.<init>(Context.java:98) at ORG.oclc.os.SRW.DSpaceLucene.SRWLuceneDatabase.getTermList(SRWLuceneDatabase.java:222) at ORG.oclc.os.SRW.SRWDatabase.doRequest(SRWDatabase.java:535) at gov.loc.www.zing.srw.srw_bindings.SRWSoapBindingImpl.scanOperation(SRWSoapBindingImpl.java:219) at gov.loc.www.zing.srw.srw_bindings.SRWSoapBindingSkeleton.scanOperation(SRWSoapBindingSkeleton.java:74) ... 45 more Caused by: java.lang.ClassNotFoundException: org.apache.commons.pool.ObjectPool at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1285) at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1119) ... 52 more

**Comment by marceloschmitt** [comment]
Another question, sorry. Is there a compatibility issue with new versions of DSpace?

**Comment by ralphlevan** [comment]
I'm sure there will be. They've surely changed their API since I wrote that code.

Ralph

________________________________
